OPTIONS = {
    
    # Updated in 2025 
    "business_identification_system": {
        "legal_entity_identifier": "Legal Entity Identifier (LEI)", 
        "bureau_van_dijk": "Bureau van Dijk",
        "duns_number": "D-U-N-S Number",
        "euid":"EUID",
        "perm_id":"PermID",
    },
    
    "climate_solution_category": {
        "yes_decarbonisation_enabler":"Yes - Decarbonisation Enabler (>50% revenue)",
        "yes_emerging_enabler":"Yes - Emerging Enabler (>10% revenue)",
        "no":"No",
    },

    "country_list": {
        "argentina": "Argentina",
        "australia": "Australia",
        "austria": "Austria",
        "belgium": "Belgium",
        "brazil": "Brazil",
        "brunei_darussalam": "Brunei Darussalam",
        "bulgaria": "Bulgaria",
        "cambodia": "Cambodia",
        "canada": "Canada",
        "chile": "Chile",
        "china": "China",
        "colombia": "Colombia",
        "costa_rica": "Costa Rica",
        "croatia": "Croatia",
        "cyprus": "Cyprus",
        "czech_republic": "Czech Republic",
        "denmark": "Denmark",
        "estonia": "Estonia",
        "finland": "Finland",
        "france": "France",
        "germany": "Germany",
        "greece": "Greece",
        "hong_kong": "Hong Kong",
        "hungary": "Hungary",
        "iceland": "Iceland",
        "india": "India",
        "indonesia": "Indonesia",
        "ireland": "Ireland",
        "israel": "Israel",
        "italy": "Italy",
        "japan": "Japan",
        "kazakhstan": "Kazakhstan",
        "republic_of_korea": "Republic of Korea",
        "latvia": "Latvia",
        "liechtenstein": "Liechtenstein",
        "lithuania": "Lithuania",
        "luxembourg": "Luxembourg",
        "malaysia": "Malaysia",
        "malta": "Malta",
        "mexico": "Mexico",
        "morocco": "Morocco",
        "netherlands": "Netherlands",
        "new_zealand": "New Zealand",
        "norway": "Norway",
        "peru": "Peru",
        "philippines": "Philippines",
        "poland": "Poland",
        "portugal": "Portugal",
        "rest_of_world": "Rest of World",
        "romania": "Romania",
        "russian_federation": "Russian Federation",
        "saudi_arabia": "Saudi Arabia",
        "singapore": "Singapore",
        "slovak_republic": "Slovak Republic",
        "slovenia": "Slovenia",
        "south_africa": "South Africa",
        "spain": "Spain",
        "sweden": "Sweden",
        "switzerland": "Switzerland",
        "taiwan": "Taiwan",
        "thailand": "Thailand",
        "tunisia": "Tunisia",
        "turkey": "Turkey",
        "united_kingdom": "United Kingdom",
        "united_states": "United States",
        "vietnam": "Vietnam"
    },


    "decarbonisation_strategy": {
        "board_oversight": "Yes, with board oversight",
        "yes_without_board_oversight": "Yes, but without board oversight",
        "no": "No"
    },

    "ems_presence_select": {
        "yes_iso_14001_certified": "Yes (ISO 14001 certified)",
        "yes_other_ems_certification": "Yes (other EMS certification)",
        "yes_without_certification": "Yes (without certification)",
        "no": "No, not in place",
    },

    "eu_country_list": {
        "austria": "Austria",
        "belgium": "Belgium",
        "bulgaria": "Bulgaria",
        "croatia": "Croatia",
        "cyprus": "Cyprus",
        "czech_republic": "Czech Republic",
        "denmark": "Denmark",
        "estonia": "Estonia",
        "finland": "Finland",
        "france": "France",
        "germany": "Germany",
        "greece": "Greece",
        "hungary": "Hungary",
        "ireland": "Ireland",
        "italy": "Italy",
        "latvia": "Latvia",
        "lithuania": "Lithuania",
        "luxembourg": "Luxembourg",
        "malta": "Malta",
        "netherlands": "Netherlands",
        "poland": "Poland",
        "portugal": "Portugal",
        "romania": "Romania",
        "slovak_republic": "Slovak Republic",
        "slovenia": "Slovenia",
        "spain": "Spain",
        "sweden": "Sweden"
    },

    #Updated in 2025
    "ghg_reduction_target": {
        "no": "No",
        "yes_not_paris": "Yes, but it is not Paris-aligned",
        "yes_paris_validated": "Yes, and it is Paris-aligned (covering Scope 1, 2, & material Scope 3), and it has not been validated by a third party (e.g., SBTi)",
        "yes_paris_not_validated":"Yes, and it is Paris-aligned, and it has been validated by a third party (e.g., SBTi)",
    },

    "ghg_scope_list": {
        "scope_1": "Yes — GHG Protocol Scope 1",
        "scope_1_2": "Yes - GHG Protocol Scope 1 and 2",
        "scope_1_2_3": "Yes - GHG Protocol Scope 1, 2, and 3",
        "other_protocol": "Yes - Other than GHG Protocol",
        "no": "No",
    },

    "ghg_scope_1_methodology": {
        "spend_based": "Spend-based",
        "activity_based": "Activity-based",
        "direct_monitoring": "Direct monitoring",
        "other": "Other",
    },

    "ghg_scope_2_methodology": {
        "location_based": "Location-based",
        "market_based": "Market-based",
        "unspecified": "Unspecified",
    },

    "ghg_scope_3_methodology": {
        "spend_based": "Spend-based",
        "activity_based": "Activity-based",
        "direct_emissions_supplier_based": "Direct emissions/supplier-based",
        "other": "Other",
    },
    
    #Added in 2025
    "ghg_scope_3_sources": {
        "scope_3_emissions_purchased_goods_and_services": "Scope 3.1 Purchased goods and services",
        "scope_3_emissions_capital_goods": "Scope 3.2 Capital goods",
        "scope_3_emissions_fuel_and_energy_related_not_in_scopes_1_2": "Scope 3.3 Fuel- and energy-related activities (not included in scope 1 or scope 2)",
        "scope_3_emissions_upstream_transportation_distribution": "Scope 3.4 Upstream transportation and distribution",
        "scope_3_emissions_waste_generated_in_operations": "Scope 3.5 Waste generated in operations",
        "scope_3_emissions_business_travel": "Scope 3.6 Business travel",
        "scope_3_emissions_employee_commuting": "Scope 3.7 Employee commuting",
        "scope_3_emissions_upstream_leased_assets": "Scope 3.8 Upstream leased assets",
        "scope_3_emissions_downstream_transportation_distribution": "Scope 3.9 Downstream transportation and distribution",
        "scope_3_emissions_processing_of_sold_products": "Scope 3.10 Processing of sold products",
        "scope_3_emissions_use_of_sold_products": "Scope 3.11 Use of sold products",
        "scope_3_emissions_endoflife_treatment_of_sold_products": "Scope 3.12 End-of-life treatment of sold products",
        "scope_3_emissions_downstream_leased_assets": "Scope 3.13 Downstream leased assets",
        "scope_3_emissions_franchises": "Scope 3.14 Franchises",
        "scope_3_emissions_investments": "Scope 3.15 Investments",
    },

    "iso_currency_code": {
        "AED": "UAE Dirham",
        "AFN": "Afghani",
        "ALL": "Lek",
        "AMD": "Armenian Dram",
        "ANG": "Netherlands Antillean Guilder",
        "AOA": "Kwanza",
        "ARS": "Argentine Peso",
        "AUD": "Australian Dollar",
        "AWG": "Aruban Florin",
        "AZN": "Azerbaijan Manat",
        "BAM": "Convertible Mark",
        "BBD": "Barbados Dollar",
        "BDT": "Taka",
        "BGN": "Bulgarian Lev",
        "BHD": "Bahraini Dinar",
        "BIF": "Burundi Franc",
        "BMD": "Bermudian Dollar",
        "BND": "Brunei Dollar",
        "BOB": "Boliviano",
        "BOV": "Mvdol",
        "BRL": "Brazilian Real",
        "BSD": "Bahamian Dollar",
        "BTN": "Ngultrum",
        "BWP": "Pula",
        "BYN": "Belarusian Ruble",
        "BZD": "Belize Dollar",
        "CAD": "Canadian Dollar",
        "CDF": "Congolese Franc",
        "CHE": "WIR Euro",
        "CHF": "Swiss Franc",
        "CHW": "WIR Franc",
        "CLF": "Unidad de Fomento",
        "CLP": "Chilean Peso",
        "CNY": "Yuan Renminbi",
        "COP": "Colombian Peso",
        "COU": "Unidad de Valor Real",
        "CRC": "Costa Rican Colon",
        "CUC": "Peso Convertible",
        "CUP": "Cuban Peso",
        "CVE": "Cabo Verde Escudo",
        "CZK": "Czech Koruna",
        "DJF": "Djibouti Franc",
        "DKK": "Danish Krone",
        "DOP": "Dominican Peso",
        "DZD": "Algerian Dinar",
        "EGP": "Egyptian Pound",
        "ERN": "Nakfa",
        "ETB": "Ethiopian Birr",
        "EUR": "Euro",
        "FJD": "Fiji Dollar",
        "FKP": "Falkland Islands Pound",
        "GBP": "Pound Sterling",
        "GEL": "Lari",
        "GHS": "Ghana Cedi",
        "GIP": "Gibraltar Pound",
        "GMD": "Dalasi",
        "GNF": "Guinean Franc",
        "GTQ": "Quetzal",
        "GYD": "Guyana Dollar",
        "HKD": "Hong Kong Dollar",
        "HNL": "Lempira",
        "HTG": "Gourde",
        "HUF": "Forint",
        "IDR": "Rupiah",
        "ILS": "New Israeli Sheqel",
        "INR": "Indian Rupee",
        "IQD": "Iraqi Dinar",
        "IRR": "Iranian Rial",
        "ISK": "Iceland Krona",
        "JMD": "Jamaican Dollar",
        "JOD": "Jordanian Dinar",
        "JPY": "Yen",
        "KES": "Kenyan Shilling",
        "KGS": "Som",
        "KHR": "Riel",
        "KMF": "Comorian Franc",
        "KPW": "North Korean Won",
        "KRW": "Won",
        "KWD": "Kuwaiti Dinar",
        "KYD": "Cayman Islands Dollar",
        "KZT": "Tenge",
        "LAK": "Lao Kip",
        "LBP": "Lebanese Pound",
        "LKR": "Sri Lanka Rupee",
        "LRD": "Liberian Dollar",
        "LSL": "Loti",
        "LYD": "Libyan Dinar",
        "MAD": "Moroccan Dirham",
        "MDL": "Moldovan Leu",
        "MGA": "Malagasy Ariary",
        "MKD": "Denar",
        "MMK": "Kyat",
        "MNT": "Tugrik",
        "MOP": "Pataca",
        "MRU": "Ouguiya",
        "MUR": "Mauritius Rupee",
        "MVR": "Rufiyaa",
        "MWK": "Malawi Kwacha",
        "MXN": "Mexican Peso",
        "MXV": "Mexican Unidad de Inversion (UDI)",
        "MYR": "Malaysian Ringgit",
        "MZN": "Mozambique Metical",
        "NAD": "Namibia Dollar",
        "NGN": "Naira",
        "NIO": "Cordoba Oro",
        "NOK": "Norwegian Krone",
        "NPR": "Nepalese Rupee",
        "NZD": "New Zealand Dollar",
        "OMR": "Rial Omani",
        "PAB": "Balboa",
        "PEN": "Sol",
        "PGK": "Kina",
        "PHP": "Philippine Peso",
        "PKR": "Pakistan Rupee",
        "PLN": "Zloty",
        "PYG": "Guarani",
        "QAR": "Qatari Rial",
        "RON": "Romanian Leu",
        "RSD": "Serbian Dinar",
        "RUB": "Russian Ruble",
        "RWF": "Rwanda Franc",
        "SAR": "Saudi Riyal",
        "SBD": "Solomon Islands Dollar",
        "SCR": "Seychelles Rupee",
        "SDG": "Sudanese Pound",
        "SEK": "Swedish Krona",
        "SGD": "Singapore Dollar",
        "SHP": "Saint Helena Pound",
        "SLE": "Leone",
        "SOS": "Somali Shilling",
        "SRD": "Surinam Dollar",
        "SSP": "South Sudanese Pound",
        "STN": "Dobra",
        "SVC": "El Salvador Colon",
        "SYP": "Syrian Pound",
        "SZL": "Lilangeni",
        "THB": "Baht",
        "TJS": "Somoni",
        "TMT": "Turkmenistan New Manat",
        "TND": "Tunisian Dinar",
        "TOP": "Pa’anga",
        "TRY": "Turkish Lira",
        "TTD": "Trinidad and Tobago Dollar",
        "TWD": "New Taiwan Dollar",
        "TZS": "Tanzanian Shilling",
        "UAH": "Hryvnia",
        "UGX": "Uganda Shilling",
        "USD": "US Dollar",
        "USN": "US Dollar (Next day)",
        "UYI": "Uruguay Peso en Unidades Indexadas (UI)",
        "UYU": "Peso Uruguayo",
        "UYW": "Unidad Previsional",
        "UZS": "Uzbekistan Sum",
        "VED": "Bolívar Soberano",
        "VES": "Bolívar Soberano",
        "VND": "Dong",
        "VUV": "Vatu",
        "WST": "Tala",
        "XAF": "CFA Franc BEAC",
        "XAG": "Silver",
        "XAU": "Gold",
        "XBA": "Bond Markets Unit European Composite Unit (EURCO)",
        "XBB": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
        "XBC": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
        "XBD": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
        "XCD": "East Caribbean Dollar",
        "XDR": "SDR (Special Drawing Right)",
        "XOF": "CFA Franc BCEAO",
        "XPD": "Palladium",
        "XPF": "CFP Franc",
        "XPT": "Platinum",
        "XSU": "Sucre",
        "XTS": "Codes specifically reserved for testing purposes",
        "XUA": "ADB Unit of Account",
        "XXX": "The codes assigned for transactions where no currency is involved",
        "YER": "Yemeni Rial",
        "ZAR": "Rand",
        "ZMW": "Zambian Kwacha",
        "ZWG": "Zimbabwe Gold"
    },

    "long_term_net_zero_goal": {
        "no_plan": "No - and no plan to set one (e.g. lack of viable pathway)",
        "no_establish_soon": "No - but we plan to establish this in the near term (<2 years)",
        "no_a_goal_but_not_net_zero": "No - we have a long-term goal but not fully aligned with a net zero pathway (i.e., NZ emissions by 2050 or sooner)",
        "yes": "Yes - aligned with a net zero pathway (i.e., NZ emissions by 2050 or sooner)",
    },

    "whistleblower_procedure": {
        "yes_eu_aligned": "Yes (aligned with the EU Whistleblower Directive)",
        "yes_not_eu_aligned": "Yes (not aligned with the EU Whistleblower Directive)",
        "no": "No",
        "no_but_a_plan": "No (but plan to in the next 12 months)",
    },

    "violations_ungc_oecd_guidelines": {
        "oecd_guidelines_for_multinational_enterprises": "OECD Guidelines for Multinational Enterprises",
        "un_guiding_principles_on_business_human_rights": "UNGC Guiding Principles on Business and Human Rights",
        "both": "Both OECD and UNGC",
    },

    "yes_no_expanded": {
        "yes": "Yes",
        "no": "No",
        "no_but_a_plan": "No but plan to in the next 12 months",
    },
    
    "nace_divisions": {
        "A_01_11": "A.01.11 - Growing of cereals, other than rice, leguminous crops and oil seeds",
        "A_01_12": "A.01.12 - Growing of rice",
        "A_01_13": "A.01.13 - Growing of vegetables and melons, roots and tubers",
        "A_01_14": "A.01.14 - Growing of sugar cane",
        "A_01_15": "A.01.15 - Growing of tobacco",
        "A_01_16": "A.01.16 - Growing of fibre crops",
        "A_01_19": "A.01.19 - Growing of other non-perennial crops",
        "A_01_21": "A.01.21 - Growing of grapes",
        "A_01_22": "A.01.22 - Growing of tropical and subtropical fruits",
        "A_01_23": "A.01.23 - Growing of citrus fruits",
        "A_01_24": "A.01.24 - Growing of pome fruits and stone fruits",
        "A_01_25": "A.01.25 - Growing of other tree and bush fruits and nuts",
        "A_01_26": "A.01.26 - Growing of oleaginous fruits",
        "A_01_27": "A.01.27 - Growing of beverage crops",
        "A_01_28": "A.01.28 - Growing of spices, aromatic, drug and pharmaceutical crops",
        "A_01_29": "A.01.29 - Growing of other perennial crops",
        "A_01_30": "A.01.30 - Plant propagation",
        "A_01_41": "A.01.41 - Raising of dairy cattle",
        "A_01_42": "A.01.42 - Raising of other cattle and buffaloes",
        "A_01_43": "A.01.43 - Raising of horses and other equines",
        "A_01_44": "A.01.44 - Raising of camels and camelids",
        "A_01_45": "A.01.45 - Raising of sheep and goats",
        "A_01_46": "A.01.46 - Raising of swine and pigs",
        "A_01_47": "A.01.47 - Raising of poultry",
        "A_01_48": "A.01.48 - Raising of other animals",
        "A_01_50": "A.01.50 - Mixed farming",
        "A_01_61": "A.01.61 - Support activities for crop production",
        "A_01_62": "A.01.62 - Support activities for animal production",
        "A_01_63": "A.01.63 - Post-harvest crop activities and seed processing for propagation",
        "A_01_70": "A.01.70 - Hunting, trapping and related service activities",
        "A_02_10": "A.02.10 - Silviculture and other forestry activities",
        "A_02_20": "A.02.20 - Logging",
        "A_02_30": "A.02.30 - Gathering of wild growing non-wood products",
        "A_02_40": "A.02.40 - Support services to forestry",
        "A_03_11": "A.03.11 - Marine fishing",
        "A_03_12": "A.03.12 - Freshwater fishing",
        "A_03_21": "A.03.21 - Marine aquaculture",
        "A_03_22": "A.03.22 - Freshwater aquaculture",
        "A_03_30": "A.03.30 - Support activities for fishing and aquaculture",
        "B_05_10": "B.05.10 - Mining of hard coal",
        "B_05_20": "B.05.20 - Mining of lignite",
        "B_06_10": "B.06.10 - Extraction of crude petroleum",
        "B_06_20": "B.06.20 - Extraction of natural gas",
        "B_07_10": "B.07.10 - Mining of iron ores",
        "B_07_21": "B.07.21 - Mining of uranium and thorium ores",
        "B_07_29": "B.07.29 - Mining of other non-ferrous metal ores",
        "B_08_11": "B.08.11 - Quarrying of ornamental stone, limestone, gypsum, slate and other stone",
        "B_08_12": "B.08.12 - Operation of gravel and sand pits and mining of clay and kaolin",
        "B_08_91": "B.08.91 - Mining of chemical and fertiliser minerals",
        "B_08_92": "B.08.92 - Extraction of peat",
        "B_08_93": "B.08.93 - Extraction of salt",
        "B_08_99": "B.08.99 - Other mining and quarrying n.e.c.",
        "B_09_10": "B.09.10 - Support activities for petroleum and natural gas extraction",
        "B_09_90": "B.09.90 - Support activities for other mining and quarrying",
        "C_10_11": "C.10.11 - Processing and preserving of meat, except of poultry meat",
        "C_10_12": "C.10.12 - Processing and preserving of poultry meat",
        "C_10_13": "C.10.13 - Production of meat and poultry meat products",
        "C_10_20": "C.10.20 - Processing and preserving of fish, crustaceans and molluscs",
        "C_10_31": "C.10.31 - Processing and preserving of potatoes",
        "C_10_32": "C.10.32 - Manufacture of fruit and vegetable juice",
        "C_10_39": "C.10.39 - Other processing and preserving of fruit and vegetables",
        "C_10_41": "C.10.41 - Manufacture of oils and fats",
        "C_10_42": "C.10.42 - Manufacture of margarine and similar edible fats",
        "C_10_51": "C.10.51 - Manufacture of dairy products",
        "C_10_52": "C.10.52 - Manufacture of ice cream and other edible ice",
        "C_10_61": "C.10.61 - Manufacture of grain mill products",
        "C_10_62": "C.10.62 - Manufacture of starches and starch products",
        "C_10_71": "C.10.71 - Manufacture of bread; manufacture of fresh pastry goods and cakes",
        "C_10_72": "C.10.72 - Manufacture of rusks, biscuits, preserved pastries and cakes",
        "C_10_73": "C.10.73 - Manufacture of farinaceous products",
        "C_10_81": "C.10.81 - Manufacture of sugar",
        "C_10_82": "C.10.82 - Manufacture of cocoa, chocolate and sugar confectionery",
        "C_10_83": "C.10.83 - Processing of tea and coffee",
        "C_10_84": "C.10.84 - Manufacture of condiments and seasonings",
        "C_10_85": "C.10.85 - Manufacture of prepared meals and dishes",
        "C_10_86": "C.10.86 - Manufacture of homogenised food preparations and dietetic food",
        "C_10_89": "C.10.89 - Manufacture of other food products n.e.c.",
        "C_10_91": "C.10.91 - Manufacture of prepared feeds for farm animals",
        "C_10_92": "C.10.92 - Manufacture of prepared pet foods",
        "C_11_01": "C.11.01 - Distilling, rectifying and blending of spirits",
        "C_11_02": "C.11.02 - Manufacture of wine from grape",
        "C_11_03": "C.11.03 - Manufacture of cider and other fruit fermented beverages",
        "C_11_04": "C.11.04 - Manufacture of other non-distilled fermented beverages",
        "C_11_05": "C.11.05 - Manufacture of beer",
        "C_11_06": "C.11.06 - Manufacture of malt",
        "C_11_07": "C.11.07 - Manufacture of soft drinks and bottled waters",
        "C_12_00": "C.12.00 - Manufacture of tobacco products",
        "C_13_10": "C.13.10 - Preparation and spinning of textile fibres",
        "C_13_20": "C.13.20 - Weaving of textiles",
        "C_13_30": "C.13.30 - Finishing of textiles",
        "C_13_91": "C.13.91 - Manufacture of knitted and crocheted fabrics",
        "C_13_92": "C.13.92 - Manufacture of household textiles and made-up furnishing articles",
        "C_13_93": "C.13.93 - Manufacture of carpets and rugs",
        "C_13_94": "C.13.94 - Manufacture of cordage, rope, twine and netting",
        "C_13_95": "C.13.95 - Manufacture of non-wovens and non-woven articles",
        "C_13_96": "C.13.96 - Manufacture of other technical and industrial textiles",
        "C_13_99": "C.13.99 - Manufacture of other textiles n.e.c.",
        "C_14_10": "C.14.10 - Manufacture of knitted and crocheted apparel",
        "C_14_21": "C.14.21 - Manufacture of outerwear",
        "C_14_22": "C.14.22 - Manufacture of underwear",
        "C_14_23": "C.14.23 - Manufacture of workwear",
        "C_14_24": "C.14.24 - Manufacture of leather clothes and fur apparel",
        "C_14_29": "C.14.29 - Manufacture of other wearing apparel and accessories n.e.c.",
        "C_15_11": "C.15.11 - Tanning, dressing, dyeing of leather and fur",
        "C_15_12": "C.15.12 - Manufacture of luggage, handbags, saddlery and harness of any material",
        "C_15_20": "C.15.20 - Manufacture of footwear",
        "C_16_11": "C.16.11 - Sawmilling and planing of wood",
        "C_16_12": "C.16.12 - Processing and finishing of wood",
        "C_16_21": "C.16.21 - Manufacture of veneer sheets and wood-based panels",
        "C_16_22": "C.16.22 - Manufacture of assembled parquet floors",
        "C_16_23": "C.16.23 - Manufacture of other builders' carpentry and joinery",
        "C_16_24": "C.16.24 - Manufacture of wooden containers",
        "C_16_25": "C.16.25 - Manufacture of doors and windows of wood",
        "C_16_26": "C.16.26 - Manufacture of solid fuels from vegetable biomass",
        "C_16_27": "C.16.27 - Finishing of wooden products",
        "C_16_28": "C.16.28 - Manufacture of other products of wood and articles of cork, straw and plaiting materials",
        "C_17_11": "C.17.11 - Manufacture of pulp",
        "C_17_12": "C.17.12 - Manufacture of paper and paperboard",
        "C_17_21": "C.17.21 - Manufacture of corrugated paper, paperboard and containers of paper and paperboard",
        "C_17_22": "C.17.22 - Manufacture of household and sanitary goods and of toilet requisites",
        "C_17_23": "C.17.23 - Manufacture of paper stationery",
        "C_17_24": "C.17.24 - Manufacture of wallpaper",
        "C_17_25": "C.17.25 - Manufacture of other articles of paper and paperboard",
        "C_18_11": "C.18.11 - Printing of newspapers",
        "C_18_12": "C.18.12 - Other printing",
        "C_18_13": "C.18.13 - Pre-press and pre-media services",
        "C_18_14": "C.18.14 - Binding and related services",
        "C_18_20": "C.18.20 - Reproduction of recorded media",
        "C_19_10": "C.19.10 - Manufacture of coke oven products",
        "C_19_20": "C.19.20 - Manufacture of refined petroleum products and fossil fuel products",
        "C_20_11": "C.20.11 - Manufacture of industrial gases",
        "C_20_12": "C.20.12 - Manufacture of dyes and pigments",
        "C_20_13": "C.20.13 - Manufacture of other inorganic basic chemicals",
        "C_20_14": "C.20.14 - Manufacture of other organic basic chemicals",
        "C_20_15": "C.20.15 - Manufacture of fertilisers and nitrogen compounds",
        "C_20_16": "C.20.16 - Manufacture of plastics in primary forms",
        "C_20_17": "C.20.17 - Manufacture of synthetic rubber in primary forms",
        "C_20_20": "C.20.20 - Manufacture of pesticides, disinfectants and other agrochemical products",
        "C_20_30": "C.20.30 - Manufacture of paints, varnishes and similar coatings, printing ink and mastics",
        "C_20_41": "C.20.41 - Manufacture of soap and detergents, cleaning and polishing preparations",
        "C_20_42": "C.20.42 - Manufacture of perfumes and toilet preparations",
        "C_20_51": "C.20.51 - Manufacture of liquid biofuels",
        "C_20_59": "C.20.59 - Manufacture of other chemical products n.e.c.",
        "C_20_60": "C.20.60 - Manufacture of man-made fibres",
        "C_21_10": "C.21.10 - Manufacture of basic pharmaceutical products",
        "C_21_20": "C.21.20 - Manufacture of pharmaceutical preparations",
        "C_22_11": "C.22.11 - Manufacture, retreading and rebuilding of rubber tyres and manufacture of tubes",
        "C_22_12": "C.22.12 - Manufacture of other rubber products",
        "C_22_21": "C.22.21 - Manufacture of plastic plates, sheets, tubes and profiles",
        "C_22_22": "C.22.22 - Manufacture of plastic packing goods",
        "C_22_23": "C.22.23 - Manufacture of doors and windows of plastic",
        "C_22_24": "C.22.24 - Manufacture of builders’ ware of plastic",
        "C_22_25": "C.22.25 - Processing and finishing of plastic products",
        "C_22_26": "C.22.26 - Manufacture of other plastic products",
        "C_23_11": "C.23.11 - Manufacture of flat glass",
        "C_23_12": "C.23.12 - Shaping and processing of flat glass",
        "C_23_13": "C.23.13 - Manufacture of hollow glass",
        "C_23_14": "C.23.14 - Manufacture of glass fibres",
        "C_23_15": "C.23.15 - Manufacture and processing of other glass, including technical glassware",
        "C_23_20": "C.23.20 - Manufacture of refractory products",
        "C_23_31": "C.23.31 - Manufacture of ceramic tiles and flags",
        "C_23_32": "C.23.32 - Manufacture of bricks, tiles and construction products, in baked clay",
        "C_23_41": "C.23.41 - Manufacture of ceramic household and ornamental articles",
        "C_23_42": "C.23.42 - Manufacture of ceramic sanitary fixtures",
        "C_23_43": "C.23.43 - Manufacture of ceramic insulators and insulating fittings",
        "C_23_44": "C.23.44 - Manufacture of other technical ceramic products",
        "C_23_45": "C.23.45 - Manufacture of other ceramic products",
        "C_23_51": "C.23.51 - Manufacture of cement",
        "C_23_52": "C.23.52 - Manufacture of lime and plaster",
        "C_23_61": "C.23.61 - Manufacture of concrete products for construction purposes",
        "C_23_62": "C.23.62 - Manufacture of plaster products for construction purposes",
        "C_23_63": "C.23.63 - Manufacture of ready-mixed concrete",
        "C_23_64": "C.23.64 - Manufacture of mortars",
        "C_23_65": "C.23.65 - Manufacture of fibre cement",
        "C_23_66": "C.23.66 - Manufacture of other articles of concrete, cement and plaster",
        "C_23_70": "C.23.70 - Cutting, shaping and finishing of stone",
        "C_23_91": "C.23.91 - Manufacture of abrasive products",
        "C_23_99": "C.23.99 - Manufacture of other non-metallic mineral products n.e.c.",
        "C_24_10": "C.24.10 - Manufacture of basic iron and steel and of ferro-alloys",
        "C_24_20": "C.24.20 - Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
        "C_24_31": "C.24.31 - Cold drawing of bars",
        "C_24_32": "C.24.32 - Cold rolling of narrow strip",
        "C_24_33": "C.24.33 - Cold forming or folding",
        "C_24_34": "C.24.34 - Cold drawing of wire",
        "C_24_41": "C.24.41 - Precious metals production",
        "C_24_42": "C.24.42 - Aluminium production",
        "C_24_43": "C.24.43 - Lead, zinc and tin production",
        "C_24_44": "C.24.44 - Copper production",
        "C_24_45": "C.24.45 - Other non-ferrous metal production",
        "C_24_46": "C.24.46 - Processing of nuclear fuel",
        "C_24_51": "C.24.51 - Casting of iron",
        "C_24_52": "C.24.52 - Casting of steel",
        "C_24_53": "C.24.53 - Casting of light metals",
        "C_24_54": "C.24.54 - Casting of other non-ferrous metals",
        "C_25_11": "C.25.11 - Manufacture of metal structures and parts of structures",
        "C_25_12": "C.25.12 - Manufacture of doors and windows of metal",
        "C_25_21": "C.25.21 - Manufacture of central heating radiators, steam generators and boilers",
        "C_25_22": "C.25.22 - Manufacture of other tanks, reservoirs and containers of metal",
        "C_25_30": "C.25.30 - Manufacture of weapons and ammunition",
        "C_25_40": "C.25.40 - Forging and shaping metal and powder metallurgy",
        "C_25_51": "C.25.51 - Coating of metals",
        "C_25_52": "C.25.52 - Heat treatment of metals",
        "C_25_53": "C.25.53 - Machining of metals",
        "C_25_61": "C.25.61 - Manufacture of cutlery",
        "C_25_62": "C.25.62 - Manufacture of locks and hinges",
        "C_25_63": "C.25.63 - Manufacture of tools",
        "C_25_91": "C.25.91 - Manufacture of steel drums and similar containers",
        "C_25_92": "C.25.92 - Manufacture of light metal packaging",
        "C_25_93": "C.25.93 - Manufacture of wire products, chain and springs",
        "C_25_94": "C.25.94 - Manufacture of fasteners and screw machine products",
        "C_25_99": "C.25.99 - Manufacture of other fabricated metal products n.e.c.",
        "C_26_11": "C.26.11 - Manufacture of electronic components",
        "C_26_12": "C.26.12 - Manufacture of loaded electronic boards",
        "C_26_20": "C.26.20 - Manufacture of computers and peripheral equipment",
        "C_26_30": "C.26.30 - Manufacture of communication equipment",
        "C_26_40": "C.26.40 - Manufacture of consumer electronics",
        "C_26_51": "C.26.51 - Manufacture of instruments and appliances for measuring, testing and navigation",
        "C_26_52": "C.26.52 - Manufacture of watches and clocks",
        "C_26_60": "C.26.60 - Manufacture of irradiation, electromedical and electrotherapeutic equipment",
        "C_26_70": "C.26.70 - Manufacture of optical instruments, magnetic and optical media and photographic equipment",
        "C_27_11": "C.27.11 - Manufacture of electric motors, generators and transformers",
        "C_27_12": "C.27.12 - Manufacture of electricity distribution and control apparatus",
        "C_27_20": "C.27.20 - Manufacture of batteries and accumulators",
        "C_27_31": "C.27.31 - Manufacture of fibre optic cables",
        "C_27_32": "C.27.32 - Manufacture of other electronic and electric wires and cables",
        "C_27_33": "C.27.33 - Manufacture of wiring devices",
        "C_27_40": "C.27.40 - Manufacture of lighting equipment",
        "C_27_51": "C.27.51 - Manufacture of electric domestic appliances",
        "C_27_52": "C.27.52 - Manufacture of non-electric domestic appliances",
        "C_27_90": "C.27.90 - Manufacture of other electrical equipment",
        "C_28_11": "C.28.11 - Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
        "C_28_12": "C.28.12 - Manufacture of fluid power equipment",
        "C_28_13": "C.28.13 - Manufacture of other pumps and compressors",
        "C_28_14": "C.28.14 - Manufacture of other taps and valves",
        "C_28_15": "C.28.15 - Manufacture of bearings, gears, gearing and driving elements",
        "C_28_21": "C.28.21 - Manufacture of ovens, furnaces and permanent household heating equipment",
        "C_28_22": "C.28.22 - Manufacture of lifting and handling equipment",
        "C_28_23": "C.28.23 - Manufacture of office machinery and equipment, except computers and peripheral equipment",
        "C_28_24": "C.28.24 - Manufacture of power-driven hand tools",
        "C_28_25": "C.28.25 - Manufacture of non-domestic air conditioning equipment",
        "C_28_29": "C.28.29 - Manufacture of other general-purpose machinery n.e.c.",
        "C_28_30": "C.28.30 - Manufacture of agricultural and forestry machinery",
        "C_28_41": "C.28.41 - Manufacture of metal forming machinery and machine tools for metal work",
        "C_28_42": "C.28.42 - Manufacture of other machine tools",
        "C_28_91": "C.28.91 - Manufacture of machinery for metallurgy",
        "C_28_92": "C.28.92 - Manufacture of machinery for mining, quarrying and construction",
        "C_28_93": "C.28.93 - Manufacture of machinery for food, beverage and tobacco processing",
        "C_28_94": "C.28.94 - Manufacture of machinery for textile, apparel and leather production",
        "C_28_95": "C.28.95 - Manufacture of machinery for paper and paperboard production",
        "C_28_96": "C.28.96 - Manufacture of plastics and rubber machinery",
        "C_28_97": "C.28.97 - Manufacture of additive manufacturing machinery",
        "C_28_99": "C.28.99 - Manufacture of other special-purpose machinery n.e.c.",
        "C_29_10": "C.29.10 - Manufacture of motor vehicles",
        "C_29_20": "C.29.20 - Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-trailers",
        "C_29_31": "C.29.31 - Manufacture of electrical and electronic equipment for motor vehicles",
        "C_29_32": "C.29.32 - Manufacture of other parts and accessories for motor vehicles",
        "C_30_11": "C.30.11 - Building of civilian ships and floating structures",
        "C_30_12": "C.30.12 - Building of pleasure and sporting boats",
        "C_30_13": "C.30.13 - Building of military ships and vessels",
        "C_30_20": "C.30.20 - Manufacture of railway locomotives and rolling stock",
        "C_30_31": "C.30.31 - Manufacture of civilian air and spacecraft and related machinery",
        "C_30_32": "C.30.32 - Manufacture of military air and spacecraft and related machinery",
        "C_30_40": "C.30.40 - Manufacture of military fighting vehicles",
        "C_30_91": "C.30.91 - Manufacture of motorcycles",
        "C_30_92": "C.30.92 - Manufacture of bicycles and invalid carriages",
        "C_30_99": "C.30.99 - Manufacture of other transport equipment n.e.c.",
        "C_31_00": "C.31.00 - Manufacture of furniture",
        "C_32_11": "C.32.11 - Striking of coins",
        "C_32_12": "C.32.12 - Manufacture of jewellery and related articles",
        "C_32_13": "C.32.13 - Manufacture of imitation jewellery and related articles",
        "C_32_20": "C.32.20 - Manufacture of musical instruments",
        "C_32_30": "C.32.30 - Manufacture of sports goods",
        "C_32_40": "C.32.40 - Manufacture of games and toys",
        "C_32_50": "C.32.50 - Manufacture of medical and dental instruments and supplies",
        "C_32_91": "C.32.91 - Manufacture of brooms and brushes",
        "C_32_99": "C.32.99 - Other manufacturing n.e.c.",
        "C_33_11": "C.33.11 - Repair and maintenance of fabricated metal products",
        "C_33_12": "C.33.12 - Repair and maintenance of machinery",
        "C_33_13": "C.33.13 - Repair and maintenance of electronic and optical equipment",
        "C_33_14": "C.33.14 - Repair and maintenance of electrical equipment",
        "C_33_15": "C.33.15 - Repair and maintenance of civilian ships and boats",
        "C_33_16": "C.33.16 - Repair and maintenance of civilian air and spacecraft",
        "C_33_17": "C.33.17 - Repair and maintenance of other civilian transport equipment",
        "C_33_18": "C.33.18 - Repair and maintenance of military fighting vehicles, ships, boats, air and spacecraft",
        "C_33_19": "C.33.19 - Repair and maintenance of other equipment",
        "C_33_20": "C.33.20 - Installation of industrial machinery and equipment",
        "D_35_11": "D.35.11 - Production of electricity from non-renewable sources",
        "D_35_12": "D.35.12 - Production of electricity from renewable sources",
        "D_35_13": "D.35.13 - Transmission of electricity",
        "D_35_14": "D.35.14 - Distribution of electricity",
        "D_35_15": "D.35.15 - Trade of electricity",
        "D_35_16": "D.35.16 - Storage of electricity",
        "D_35_21": "D.35.21 - Manufacture of gas",
        "D_35_22": "D.35.22 - Distribution of gaseous fuels through mains",
        "D_35_23": "D.35.23 - Trade of gas through mains",
        "D_35_24": "D.35.24 - Storage of gas as part of network supply services",
        "D_35_30": "D.35.30 - Steam and air conditioning supply",
        "D_35_40": "D.35.40 - Activities of brokers and agents for electric power and natural gas",
        "E_36_00": "E.36.00 - Water collection, treatment and supply",
        "E_37_00": "E.37.00 - Sewerage",
        "E_38_11": "E.38.11 - Collection of non-hazardous waste",
        "E_38_12": "E.38.12 - Collection of hazardous waste",
        "E_38_21": "E.38.21 - Materials recovery",
        "E_38_22": "E.38.22 - Energy recovery",
        "E_38_23": "E.38.23 - Other waste recovery",
        "E_38_31": "E.38.31 - Incineration without energy recovery",
        "E_38_32": "E.38.32 - Landfilling or permanent storage",
        "E_38_33": "E.38.33 - Other waste disposal",
        "E_39_00": "E.39.00 - Remediation activities and other waste management service activities",
        "F_41_00": "F.41.00 - Construction of residential and non-residential buildings",
        "F_42_11": "F.42.11 - Construction of roads and motorways",
        "F_42_12": "F.42.12 - Construction of railways and underground railways",
        "F_42_13": "F.42.13 - Construction of bridges and tunnels",
        "F_42_21": "F.42.21 - Construction of utility projects for fluids",
        "F_42_22": "F.42.22 - Construction of utility projects for electricity and telecommunications",
        "F_42_91": "F.42.91 - Construction of water projects",
        "F_42_99": "F.42.99 - Construction of other civil engineering projects n.e.c.",
        "F_43_11": "F.43.11 - Demolition",
        "F_43_12": "F.43.12 - Site preparation",
        "F_43_13": "F.43.13 - Test drilling and boring",
        "F_43_21": "F.43.21 - Electrical installation",
        "F_43_22": "F.43.22 - Plumbing, heat and air-conditioning installation",
        "F_43_23": "F.43.23 - Installation of insulation",
        "F_43_24": "F.43.24 - Other construction installation",
        "F_43_31": "F.43.31 - Plastering",
        "F_43_32": "F.43.32 - Joinery installation",
        "F_43_33": "F.43.33 - Floor and wall covering",
        "F_43_34": "F.43.34 - Painting and glazing",
        "F_43_35": "F.43.35 - Other building completion and finishing",
        "F_43_41": "F.43.41 - Roofing activities",
        "F_43_42": "F.43.42 - Other specialised construction activities in construction of buildings",
        "F_43_50": "F.43.50 - Specialised construction activities in civil engineering",
        "F_43_60": "F.43.60 - Intermediation service activities for specialised construction services",
        "F_43_91": "F.43.91 - Masonry and bricklaying activities",
        "F_43_99": "F.43.99 - Other specialised construction activities n.e.c.",
        "G_46_11": "G.46.11 - Activities of agents involved in the wholesale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",
        "G_46_12": "G.46.12 - Activities of agents involved in the wholesale of fuels, ores, metals and industrial chemicals",
        "G_46_13": "G.46.13 - Activities of agents involved in the wholesale of timber and building materials",
        "G_46_14": "G.46.14 - Activities of agents involved in the wholesale of machinery, industrial equipment, ships and aircraft",
        "G_46_15": "G.46.15 - Activities of agents involved in the wholesale of furniture, household goods, hardware and ironmongery",
        "G_46_16": "G.46.16 - Activities of agents involved in the wholesale of textiles, clothing, fur, footwear and leather goods",
        "G_46_17": "G.46.17 - Activities of agents involved in the wholesale of food, beverages and tobacco",
        "G_46_18": "G.46.18 - Activities of agents involved in the wholesale of other particular products",
        "G_46_19": "G.46.19 - Activities of agents involved in non-specialised wholesale",
        "G_46_21": "G.46.21 - Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
        "G_46_22": "G.46.22 - Wholesale of flowers and plants",
        "G_46_23": "G.46.23 - Wholesale of live animals",
        "G_46_24": "G.46.24 - Wholesale of hides, skins and leather",
        "G_46_31": "G.46.31 - Wholesale of fruit and vegetables",
        "G_46_32": "G.46.32 - Wholesale of meat, meat products, fish and fish products",
        "G_46_33": "G.46.33 - Wholesale of dairy products, eggs and edible oils and fats",
        "G_46_34": "G.46.34 - Wholesale of beverages",
        "G_46_35": "G.46.35 - Wholesale of tobacco products",
        "G_46_36": "G.46.36 - Wholesale of sugar, chocolate and sugar confectionery",
        "G_46_37": "G.46.37 - Wholesale of coffee, tea, cocoa and spices",
        "G_46_38": "G.46.38 - Wholesale of other food",
        "G_46_39": "G.46.39 - Non-specialised wholesale of food, beverages and tobacco",
        "G_46_41": "G.46.41 - Wholesale of textiles",
        "G_46_42": "G.46.42 - Wholesale of clothing and footwear",
        "G_46_43": "G.46.43 - Wholesale of electrical household appliances",
        "G_46_44": "G.46.44 - Wholesale of china and glassware and cleaning materials",
        "G_46_45": "G.46.45 - Wholesale of perfume and cosmetics",
        "G_46_46": "G.46.46 - Wholesale of pharmaceutical and medical goods",
        "G_46_47": "G.46.47 - Wholesale of household, office and shop furniture, carpets and lighting equipment",
        "G_46_48": "G.46.48 - Wholesale of watches and jewellery",
        "G_46_49": "G.46.49 - Wholesale of other household goods",
        "G_46_50": "G.46.50 - Wholesale of information and communication equipment",
        "G_46_61": "G.46.61 - Wholesale of agricultural machinery, equipment and supplies",
        "G_46_62": "G.46.62 - Wholesale of machine tools",
        "G_46_63": "G.46.63 - Wholesale of mining, construction and civil engineering machinery",
        "G_46_64": "G.46.64 - Wholesale of other machinery and equipment",
        "G_46_71": "G.46.71 - Wholesale of motor vehicles",
        "G_46_72": "G.46.72 - Wholesale of motor vehicle parts and accessories",
        "G_46_73": "G.46.73 - Wholesale of motorcycles, motorcycle parts and accessories",
        "G_46_81": "G.46.81 - Wholesale of solid, liquid and gaseous fuels and related products",
        "G_46_82": "G.46.82 - Wholesale of metals and metal ores",
        "G_46_83": "G.46.83 - Wholesale of wood, construction materials and sanitary equipment",
        "G_46_84": "G.46.84 - Wholesale of hardware, plumbing and heating equipment and supplies",
        "G_46_85": "G.46.85 - Wholesale of chemical products",
        "G_46_86": "G.46.86 - Wholesale of other intermediate products",
        "G_46_87": "G.46.87 - Wholesale of waste and scrap",
        "G_46_89": "G.46.89 - Other specialised wholesale",
        "G_46_90": "G.46.90 - Non-specialised wholesale trade",
        "G_47_11": "G.47.11 - Non-specialised retail sale of predominately food, beverages or tobacco",
        "G_47_12": "G.47.12 - Other non-specialised retail sale",
        "G_47_21": "G.47.21 - Retail sale of fruit and vegetables",
        "G_47_22": "G.47.22 - Retail sale of meat and meat products",
        "G_47_23": "G.47.23 - Retail sale of fish, crustaceans and molluscs",
        "G_47_24": "G.47.24 - Retail sale of bread, cake and confectionery",
        "G_47_25": "G.47.25 - Retail sale of beverages",
        "G_47_26": "G.47.26 - Retail sale of tobacco products",
        "G_47_27": "G.47.27 - Retail sale of other food",
        "G_47_30": "G.47.30 - Retail sale of automotive fuel",
        "G_47_40": "G.47.40 - Retail sale of information and communication equipment",
        "G_47_51": "G.47.51 - Retail sale of textiles",
        "G_47_52": "G.47.52 - Retail sale of hardware, building materials, paints and glass",
        "G_47_53": "G.47.53 - Retail sale of carpets, rugs, wall and floor coverings",
        "G_47_54": "G.47.54 - Retail sale of electrical household appliances",
        "G_47_55": "G.47.55 - Retail sale of furniture, lighting equipment, tableware and other household goods",
        "G_47_61": "G.47.61 - Retail sale of books",
        "G_47_62": "G.47.62 - Retail sale of newspapers, and other periodical publications and stationery",
        "G_47_63": "G.47.63 - Retail sale of sporting equipment",
        "G_47_64": "G.47.64 - Retail sale of games and toys",
        "G_47_69": "G.47.69 - Retail sale of cultural and recreational goods n.e.c.",
        "G_47_71": "G.47.71 - Retail sale of clothing",
        "G_47_72": "G.47.72 - Retail sale of footwear and leather goods",
        "G_47_73": "G.47.73 - Retail sale of pharmaceutical products",
        "G_47_74": "G.47.74 - Retail sale of medical and orthopaedic goods",
        "G_47_75": "G.47.75 - Retail sale of cosmetic and toilet articles",
        "G_47_76": "G.47.76 - Retail sale of flowers, plants, fertilisers, pets and pet food",
        "G_47_77": "G.47.77 - Retail sale of watches and jewellery",
        "G_47_78": "G.47.78 - Retail sale of other new goods",
        "G_47_79": "G.47.79 - Retail sale of second-hand goods",
        "G_47_81": "G.47.81 - Retail sale of motor vehicles",
        "G_47_82": "G.47.82 - Retail sale of motor vehicle parts and accessories",
        "G_47_83": "G.47.83 - Retail sale of motorcycles, motorcycle parts and accessories",
        "G_47_91": "G.47.91 - Intermediation service activities for non-specialised retail sale",
        "G_47_92": "G.47.92 - Intermediation service activities for specialised retail sale",
        "H_49_11": "H.49.11 - Passenger heavy rail transport",
        "H_49_12": "H.49.12 - Other passenger rail transport",
        "H_49_20": "H.49.20 - Freight rail transport",
        "H_49_31": "H.49.31 - Scheduled passenger transport by road",
        "H_49_32": "H.49.32 - Non-scheduled passenger transport by road",
        "H_49_33": "H.49.33 - On-demand passenger transport service activities by vehicle with driver",
        "H_49_34": "H.49.34 - Passenger transport by cableways and ski lifts",
        "H_49_39": "H.49.39 - Other passenger land transport n.e.c.",
        "H_49_41": "H.49.41 - Freight transport by road",
        "H_49_42": "H.49.42 - Removal services",
        "H_49_50": "H.49.50 - Transport via pipeline",
        "H_50_10": "H.50.10 - Sea and coastal passenger water transport",
        "H_50_20": "H.50.20 - Sea and coastal freight water transport",
        "H_50_30": "H.50.30 - Inland passenger water transport",
        "H_50_40": "H.50.40 - Inland freight water transport",
        "H_51_10": "H.51.10 - Passenger air transport",
        "H_51_21": "H.51.21 - Freight air transport",
        "H_51_22": "H.51.22 - Space transport",
        "H_52_10": "H.52.10 - Warehousing and storage",
        "H_52_21": "H.52.21 - Service activities incidental to land transportation",
        "H_52_22": "H.52.22 - Service activities incidental to water transportation",
        "H_52_23": "H.52.23 - Service activities incidental to air transportation",
        "H_52_24": "H.52.24 - Cargo handling",
        "H_52_25": "H.52.25 - Logistics service activities",
        "H_52_26": "H.52.26 - Other support activities for transportation",
        "H_52_31": "H.52.31 - Intermediation service activities for freight transportation",
        "H_52_32": "H.52.32 - Intermediation service activities for passenger transportation",
        "H_53_10": "H.53.10 - Postal activities under universal service obligation",
        "H_53_20": "H.53.20 - Other postal and courier activities",
        "H_53_30": "H.53.30 - Intermediation service activities for postal and courier activities",
        "I_55_10": "I.55.10 - Hotels and similar accommodation",
        "I_55_20": "I.55.20 - Holiday and other short-stay accommodation",
        "I_55_30": "I.55.30 - Camping grounds and recreational vehicle parks",
        "I_55_40": "I.55.40 - Intermediation service activities for accommodation",
        "I_55_90": "I.55.90 - Other accommodation",
        "I_56_11": "I.56.11 - Restaurant activities",
        "I_56_12": "I.56.12 - Mobile food service activities",
        "I_56_21": "I.56.21 - Event catering activities",
        "I_56_22": "I.56.22 - Contract catering service activities and other food service activities",
        "I_56_30": "I.56.30 - Beverage serving activities",
        "I_56_40": "I.56.40 - Intermediation service activities for food and beverage services activities",
        "J_58_11": "J.58.11 - Publishing of books",
        "J_58_12": "J.58.12 - Publishing of newspapers",
        "J_58_13": "J.58.13 - Publishing of journals and periodicals",
        "J_58_19": "J.58.19 - Other publishing activities, except software publishing",
        "J_58_21": "J.58.21 - Publishing of video games",
        "J_58_29": "J.58.29 - Other software publishing",
        "J_59_11": "J.59.11 - Motion picture, video and television programme production activities",
        "J_59_12": "J.59.12 - Motion picture, video and television programme post-production activities",
        "J_59_13": "J.59.13 - Motion picture and video distribution activities",
        "J_59_14": "J.59.14 - Motion picture projection activities",
        "J_59_20": "J.59.20 - Sound recording and music publishing activities",
        "J_60_10": "J.60.10 - Radio broadcasting and audio distribution activities",
        "J_60_20": "J.60.20 - Television programming, broadcasting and video distribution activities",
        "J_60_31": "J.60.31 - News agency activities",
        "J_60_39": "J.60.39 - Other content distribution activities",
        "K_61_10": "K.61.10 - Wired, wireless, and satellite telecommunication activities",
        "K_61_20": "K.61.20 - Telecommunication reselling activities and intermediation service activities for telecommunication",
        "K_61_90": "K.61.90 - Other telecommunication activities",
        "K_62_10": "K.62.10 - Computer programming activities",
        "K_62_20": "K.62.20 - Computer consultancy and computer facilities management activities",
        "K_62_90": "K.62.90 - Other information technology and computer service activities",
        "K_63_10": "K.63.10 - Computing infrastructure, data processing, hosting and related activities",
        "K_63_91": "K.63.91 - Web search portal activities",
        "K_63_92": "K.63.92 - Other information service activities",
        "L_64_11": "L.64.11 - Central banking",
        "L_64_19": "L.64.19 - Other monetary intermediation",
        "L_64_21": "L.64.21 - Activities of holding companies",
        "L_64_22": "L.64.22 - Activities of financing conduits",
        "L_64_31": "L.64.31 - Activities of money market and non-money market investments funds",
        "L_64_32": "L.64.32 - Activities of trust, estate and agency accounts",
        "L_64_91": "L.64.91 - Financial leasing",
        "L_64_92": "L.64.92 - Other credit granting",
        "L_64_99": "L.64.99 - Other financial service activities, except insurance and pension funding n.e.c.",
        "L_65_11": "L.65.11 - Life insurance",
        "L_65_12": "L.65.12 - Non-life insurance",
        "L_65_20": "L.65.20 - Reinsurance",
        "L_65_30": "L.65.30 - Pension funding",
        "L_66_11": "L.66.11 - Administration of financial markets",
        "L_66_12": "L.66.12 - Security and commodity contracts brokerage",
        "L_66_19": "L.66.19 - Other activities auxiliary to financial services, except insurance and pension funding",
        "L_66_21": "L.66.21 - Risk and damage evaluation",
        "L_66_22": "L.66.22 - Activities of insurance agents and brokers",
        "L_66_29": "L.66.29 - Activities auxiliary to insurance and pension funding n.e.c.",
        "L_66_30": "L.66.30 - Fund management activities",
        "M_68_11": "M.68.11 - Buying and selling of own real estate",
        "M_68_12": "M.68.12 - Development of building projects",
        "M_68_20": "M.68.20 - Rental and operating of own or leased real estate",
        "M_68_31": "M.68.31 - Intermediation service activities for real estate activities",
        "M_68_32": "M.68.32 - Other real estate activities on a fee or contract basis",
        "N_69_10": "N.69.10 - Legal activities",
        "N_69_20": "N.69.20 - Accounting, bookkeeping and auditing activities; tax consultancy",
        "N_70_10": "N.70.10 - Activities of head offices",
        "N_70_20": "N.70.20 - Business and other management consultancy activities",
        "N_71_11": "N.71.11 - Architectural activities",
        "N_71_12": "N.71.12 - Engineering activities and related technical consultancy",
        "N_71_20": "N.71.20 - Technical testing and analysis",
        "N_72_10": "N.72.10 - Research and experimental development on natural sciences and engineering",
        "N_72_20": "N.72.20 - Research and experimental development on social sciences and humanities",
        "N_73_11": "N.73.11 - Activities of advertising agencies",
        "N_73_12": "N.73.12 - Media representation",
        "N_73_20": "N.73.20 - Market research and public opinion polling",
        "N_73_30": "N.73.30 - Public relations and communication activities",
        "N_74_11": "N.74.11 - Industrial product and fashion design activities",
        "N_74_12": "N.74.12 - Graphic design and visual communication activities",
        "N_74_13": "N.74.13 - Interior design activities",
        "N_74_14": "N.74.14 - Other specialised design activities",
        "N_74_20": "N.74.20 - Photographic activities",
        "N_74_30": "N.74.30 - Translation and interpretation activities",
        "N_74_91": "N.74.91 - Patent brokering and marketing service activities",
        "N_74_99": "N.74.99 - All other professional, scientific and technical activities n.e.c.",
        "N_75_00": "N.75.00 - Veterinary activities",
        "O_77_11": "O.77.11 - Rental and leasing of cars and light motor vehicles",
        "O_77_12": "O.77.12 - Rental and leasing of trucks",
        "O_77_21": "O.77.21 - Rental and leasing of recreational and sports goods",
        "O_77_22": "O.77.22 - Rental and leasing of other personal and household goods",
        "O_77_31": "O.77.31 - Rental and leasing of agricultural machinery and equipment",
        "O_77_32": "O.77.32 - Rental and leasing of construction and civil engineering machinery and equipment",
        "O_77_33": "O.77.33 - Rental and leasing of office machinery, equipment and computers",
        "O_77_34": "O.77.34 - Rental and leasing of water transport equipment",
        "O_77_35": "O.77.35 - Rental and leasing of air transport equipment",
        "O_77_39": "O.77.39 - Rental and leasing of other machinery, equipment and tangible goods n.e.c.",
        "O_77_40": "O.77.40 - Leasing of intellectual property and similar products, except copyrighted works",
        "O_77_51": "O.77.51 - Intermediation service activities for rental and leasing of cars, motorhomes and trailers",
        "O_77_52": "O.77.52 - Intermediation service activities for rental and leasing of other tangible goods and non-financial intangible assets",
        "O_78_10": "O.78.10 - Activities of employment placement agencies",
        "O_78_20": "O.78.20 - Temporary employment agency activities and other human resource provisions",
        "O_79_11": "O.79.11 - Travel agency activities",
        "O_79_12": "O.79.12 - Tour operator activities",
        "O_79_90": "O.79.90 - Other reservation service and related activities",
        "O_80_01": "O.80.01 - Investigation and private security activities",
        "O_80_09": "O.80.09 - Security activities n.e.c.",
        "O_81_10": "O.81.10 - Combined facilities support activities",
        "O_81_21": "O.81.21 - General cleaning of buildings",
        "O_81_22": "O.81.22 - Other building and industrial cleaning activities",
        "O_81_23": "O.81.23 - Other cleaning activities",
        "O_81_30": "O.81.30 - Landscape service activities",
        "O_82_10": "O.82.10 - Office administrative and support activities",
        "O_82_20": "O.82.20 - Activities of call centres",
        "O_82_30": "O.82.30 - Organisation of conventions and trade shows",
        "O_82_40": "O.82.40 - Intermediation service activities for business support service activities n.e.c.",
        "O_82_91": "O.82.91 - Activities of collection agencies and credit bureaus",
        "O_82_92": "O.82.92 - Packaging activities",
        "O_82_99": "O.82.99 - Other business support service activities n.e.c.",
        "P_84_11": "P.84.11 - General public administration activities",
        "P_84_12": "P.84.12 - Regulation of health care, education, cultural services and other social services",
        "P_84_13": "P.84.13 - Regulation of and contribution to more efficient operation of businesses",
        "P_84_21": "P.84.21 - Foreign affairs",
        "P_84_22": "P.84.22 - Defence activities",
        "P_84_23": "P.84.23 - Justice and judicial activities",
        "P_84_24": "P.84.24 - Public order and safety activities",
        "P_84_25": "P.84.25 - Fire service activities",
        "P_84_30": "P.84.30 - Compulsory social security activities",
        "Q_85_10": "Q.85.10 - Pre-primary education",
        "Q_85_20": "Q.85.20 - Primary education",
        "Q_85_31": "Q.85.31 - General secondary education",
        "Q_85_32": "Q.85.32 - Vocational secondary education",
        "Q_85_33": "Q.85.33 - Post-secondary non-tertiary education",
        "Q_85_40": "Q.85.40 - Tertiary education",
        "Q_85_51": "Q.85.51 - Sports and recreation education",
        "Q_85_52": "Q.85.52 - Cultural education",
        "Q_85_53": "Q.85.53 - Driving school activities",
        "Q_85_59": "Q.85.59 - Other education n.e.c.",
        "Q_85_61": "Q.85.61 - Intermediation service activities for courses and tutors",
        "Q_85_69": "Q.85.69 - Educational support activities n.e.c.",
        "R_86_10": "R.86.10 - Hospital activities",
        "R_86_21": "R.86.21 - General medical practice activities",
        "R_86_22": "R.86.22 - Medical specialists activities",
        "R_86_23": "R.86.23 - Dental practice care activities",
        "R_86_91": "R.86.91 - Diagnostic imaging services and medical laboratory activities",
        "R_86_92": "R.86.92 - Patient transportation by ambulance",
        "R_86_93": "R.86.93 - Activities of psychologists and psychotherapists, except medical doctors",
        "R_86_94": "R.86.94 - Nursing and midwifery activities",
        "R_86_95": "R.86.95 - Physiotherapy activities",
        "R_86_96": "R.86.96 - Traditional, complementary and alternative medicine activities",
        "R_86_97": "R.86.97 - Intermediation service activities for medical, dental and other human health services",
        "R_86_99": "R.86.99 - Other human health activities n.e.c.",
        "R_87_10": "R.87.10 - Residential nursing care activities",
        "R_87_20": "R.87.20 - Residential care activities for persons living with or having a diagnosis of a mental illness or substance abuse",
        "R_87_30": "R.87.30 - Residential care activities for older persons or persons with physical disabilities",
        "R_87_91": "R.87.91 - Intermediation service activities for residential care activities",
        "R_87_99": "R.87.99 - Other residential care activities n.e.c.",
        "R_88_10": "R.88.10 - Social work activities without accommodation for older persons or persons with disabilities",
        "R_88_91": "R.88.91 - Child day-care activities",
        "R_88_99": "R.88.99 - Other social work activities without accommodation n.e.c.",
        "S_90_11": "S.90.11 - Literary creation and musical composition activities",
        "S_90_12": "S.90.12 - Visual arts creation activities",
        "S_90_13": "S.90.13 - Other arts creation activities",
        "S_90_20": "S.90.20 - Activities of performing arts",
        "S_90_31": "S.90.31 - Operation of arts facilities and sites",
        "S_90_39": "S.90.39 - Other support activities to arts and performing arts",
        "S_91_11": "S.91.11 - Library activities",
        "S_91_12": "S.91.12 - Archive activities",
        "S_91_21": "S.91.21 - Museum and collection activities",
        "S_91_22": "S.91.22 - Historical site and monument activities",
        "S_91_30": "S.91.30 - Conservation, restoration and other support activities for cultural heritage",
        "S_91_41": "S.91.41 - Botanical and zoological garden activities",
        "S_91_42": "S.91.42 - Nature reserve activities",
        "S_92_00": "S.92.00 - Gambling and betting activities",
        "S_93_11": "S.93.11 - Operation of sports facilities",
        "S_93_12": "S.93.12 - Activities of sports clubs",
        "S_93_13": "S.93.13 - Activities of fitness centres",
        "S_93_19": "S.93.19 - Sports activities n.e.c.",
        "S_93_21": "S.93.21 - Activities of amusement parks and theme parks",
        "S_93_29": "S.93.29 - Amusement and recreation activities n.e.c.",
        "T_94_11": "T.94.11 - Activities of business and employers membership organisations",
        "T_94_12": "T.94.12 - Activities of professional membership organisations",
        "T_94_20": "T.94.20 - Activities of trade unions",
        "T_94_91": "T.94.91 - Activities of religious organisations",
        "T_94_92": "T.94.92 - Activities of political organisations",
        "T_94_99": "T.94.99 - Activities of other membership organisations n.e.c.",
        "T_95_10": "T.95.10 - Repair and maintenance of computers and communication equipment",
        "T_95_21": "T.95.21 - Repair and maintenance of consumer electronics",
        "T_95_22": "T.95.22 - Repair and maintenance of household appliances and home and garden equipment",
        "T_95_23": "T.95.23 - Repair and maintenance of footwear and leather goods",
        "T_95_24": "T.95.24 - Repair and maintenance of furniture and home furnishings",
        "T_95_25": "T.95.25 - Repair and maintenance of watches, clocks and jewellery",
        "T_95_29": "T.95.29 - Repair and maintenance of personal and household goods n.e.c.",
        "T_95_31": "T.95.31 - Repair and maintenance of motor vehicles",
        "T_95_32": "T.95.32 - Repair and maintenance of motorcycles",
        "T_95_40": "T.95.40 - Intermediation service activities for repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles",
        "T_96_10": "T.96.10 - Washing and cleaning of textile and fur products",
        "T_96_21": "T.96.21 - Hairdressing and barber activities",
        "T_96_22": "T.96.22 - Beauty care and other beauty treatment activities",
        "T_96_23": "T.96.23 - Day spa, sauna and steam bath activities",
        "T_96_30": "T.96.30 - Funeral and related activities",
        "T_96_40": "T.96.40 - Intermediation service activities for personal services",
        "T_96_91": "T.96.91 - Provision of domestic personal service activities",
        "T_96_99": "T.96.99 - Other personal service activities n.e.c.",
        "U_97_00": "U.97.00 - Activities of households as employers of domestic personnel",
        "U_98_10": "U.98.10 - Undifferentiated goods-producing activities of private households for own use",
        "U_98_20": "U.98.20 - Undifferentiated service-producing activities of private households for own use",
        "V_99_00": "V.99.00 - Activities of extraterritorial organisations and bodies"
    },
}
